export default async function generate(siteData) {
  const i18n = siteData.i18n[siteData.config.language_primary] || Object.values(siteData.i18n)[0] || {};
  const generated = i18n.generated_by || 'Generated by';
  const withText = i18n.with || 'with';
  const html = `<p class="footer-text">
  <span>${generated}</span>
  <a href="https://zine-ssg.io">Zine</a>
  <span>${withText}</span>
  <a href="https://notizine.sccl.cc">notizine</a>
</p>`;
  return { html };
}
