import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homeLink } from '../../lib/api.mjs';
import { v2Slots } from '../../lib/render.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const modulePath = (name, file) => join(REPO, 'modules', name, file);
const loadGen = async name => (await import(new URL(`../../../modules/${name}/generator.mjs`, import.meta.url).href)).default;

function page(locale, link, title = '') {
  return { locale, link, title, isSection: true };
}

const MODEL = {
  config: {
    site: {
      locales: [
        { code: 'en', output_prefix_override: '' },
        { code: 'ru', output_prefix_override: null },
      ],
      social: {},
      features: {},
    },
  },
  pages: [page('en', '/', 'notizine EN'), page('ru', '/ru/', 'notizine RU')],
};

const t = map => key => map[key] ?? key;
const RU = t({ generated_by: 'Сгенерировано', with: 'с помощью' });
const EN = t({ generated_by: 'Generated by', with: 'with' });

function captureWarn(fn) {
  const warns = [];
  const orig = console.warn;
  console.warn = msg => warns.push(String(msg));
  try {
    return { result: fn(), warns };
  } finally {
    console.warn = orig;
  }
}

test('spacer keeps its static template', () => {
  assert.equal(readFileSync(modulePath('spacer', 'template.html'), 'utf-8'), '<span class="flex-spacer"></span>');
});

test('divider template carries the divider class', () => {
  assert.equal(readFileSync(modulePath('divider', 'template.html'), 'utf-8'), '<hr class="divider">');
});

test('back_to_top anchors to #top and ships a scroll client', () => {
  assert.equal(
    readFileSync(modulePath('back_to_top', 'template.html'), 'utf-8'),
    '<a href="#top" class="back-to-top">&#8593;</a>'
  );
  assert.ok(existsSync(modulePath('back_to_top', 'client.js')));
});

test('header renders locale home link and title', async () => {
  const gen = await loadGen('header');
  const html = await gen({ page: page('en', '/about/'), site: MODEL, params: {} });
  assert.equal(html, '<a href="/" class="site-title">notizine EN</a>');
  const ru = await gen({ page: page('ru', '/ru/posts/x/'), site: MODEL, params: {} });
  assert.equal(ru, '<a href="/ru/" class="site-title">notizine RU</a>');
  assert.equal(homeLink(MODEL, { locale: 'ru' }), '/ru/');
});

test('header falls back to slash and instance title without a home page', async () => {
  const gen = await loadGen('header');
  const html = await gen({ page: page('xx', '/xx/'), site: MODEL, params: { title: 'Fallback' } });
  assert.equal(html, '<a href="/" class="site-title">Fallback</a>');
});

test('footer_text localizes generated_by attribution links', async () => {
  const gen = await loadGen('footer_text');
  const en = await gen({ i18n: EN });
  assert.equal(
    en,
    '<p class="footer-text"><span>Generated by</span> <a href="https://zine-ssg.io">Zine</a> <span>with</span> <a href="https://notizine.sccl.cc">notizine</a></p>'
  );
  const ru = await gen({ i18n: RU });
  assert.ok(ru.includes('<span>Сгенерировано</span>'));
  assert.ok(ru.includes('<span>с помощью</span>'));
});

test('badges defaults to the legacy markup and honors params.items', async () => {
  const gen = await loadGen('badges');
  const def = await gen({ params: {} });
  assert.equal(def, readFileSync(modulePath('badges', 'template.html'), 'utf-8'));
  assert.ok(def.includes('https://zine-ssg.io/'));
  const custom = await gen({
    params: { id: 'badges', module: 'badges', items: [{ href: 'https://x.example/', src: 'data:image/gif;base64,R0=', alt: 'X <1>' }] },
  });
  assert.ok(custom.includes('href="https://x.example/"'));
  assert.ok(custom.includes('alt="X &lt;1&gt;"'));
  assert.ok(!custom.includes('zine-ssg.io'));
});

test('social renders configured github and mastodon links only', async () => {
  const gen = await loadGen('social');
  const both = await gen({ site: { config: { social: { github: 'octocat', mastodon: 'https://mastodon.social/@octo' } } } });
  assert.ok(both.includes('<a href="https://github.com/octocat" class="social-link" target="_blank" rel="noopener">GitHub</a>'));
  assert.ok(both.includes('<a href="https://mastodon.social/@octo" rel="me" class="social-link">Mastodon</a>'));
  const ghOnly = await gen({ site: { config: { social: { github: 'octocat', mastodon: '' } } } });
  assert.ok(ghOnly.includes('github.com/octocat'));
  assert.ok(!ghOnly.includes('mastodon.social'));
  const empty = await gen({ site: { config: { social: {} } } });
  assert.equal(empty, '');
});

test('rss_link follows features.rss and points at locale posts feed', async () => {
  const gen = await loadGen('rss_link');
  const model = {
    config: { features: { rss: true } },
    pages: [
      { locale: 'en', isSection: true, link: '/posts/' },
      { locale: 'ru', isSection: true, link: '/ru/posts/' },
    ],
  };
  const en = await gen({ page: { locale: 'en' }, site: model });
  assert.equal(en, '<a href="/posts/index.xml" class="rss-link">RSS</a>');
  const ru = await gen({ page: { locale: 'ru' }, site: model });
  assert.equal(ru, '<a href="/ru/posts/index.xml" class="rss-link">RSS</a>');
  assert.equal(await gen({ page: { locale: 'en' }, site: { config: { features: { rss: false } }, pages: model.pages } }), '');
  assert.equal(await gen({ page: { locale: 'de' }, site: model }), '');
});

test('v2Slots no longer drops migrated sitewide or per-page modules', () => {
  const { result, warns } = captureWarn(() =>
    v2Slots({ footer: [['_social', '_rss_link']], before_main: [['_breadcrumbs', '_prev_next']] })
  );
  assert.deepEqual(result.footer, [[{ module: '_social', id: '_social' }, { module: '_rss_link', id: '_rss_link' }]]);
  assert.deepEqual(result.before_main, [[
    { module: '_breadcrumbs', id: '_breadcrumbs' },
    { module: '_prev_next', id: '_prev_next' },
  ]]);
  assert.deepEqual(warns, []);
});

function leaf(locale, link, extra = {}) {
  return {
    locale,
    link,
    title: '',
    description: '',
    date: '',
    moddate: '',
    tags: [],
    isSection: false,
    parentLink: null,
    wordcount: 0,
    readtime: 1,
    filePath: '',
    ...extra,
  };
}

const FAKE_MODEL = {
  config: {
    site: {
      locales: [
        { code: 'en', output_prefix_override: '' },
        { code: 'ru', output_prefix_override: null },
      ],
    },
  },
  pages: [
    leaf('en', '/', { title: 'notizine EN', isSection: true }),
    leaf('en', '/posts/', { title: 'Posts', isSection: true, parentLink: '/' }),
    leaf('en', '/about/', { title: 'About', parentLink: '/' }),
    leaf('en', '/posts/a/', { title: 'Post A', date: '2026-02-01', parentLink: '/posts/', filePath: '/c/en/posts/a.smd' }),
    leaf('en', '/posts/b/', { title: 'Post B', date: '2026-03-01', parentLink: '/posts/', filePath: '/c/en/posts/b.smd' }),
    leaf('ru', '/ru/', { title: 'notizine RU', isSection: true }),
    leaf('ru', '/ru/posts/', { title: 'Записи', isSection: true, parentLink: '/ru/' }),
    leaf('ru', '/ru/posts/b/', { title: 'Пост Б', date: '2026-03-01', parentLink: '/ru/posts/', filePath: '/c/ru/posts/b.smd' }),
  ],
};

test('breadcrumbs renders home, parent section and escaped page title', async () => {
  const gen = await loadGen('breadcrumbs');
  const nested = await gen({
    page: FAKE_MODEL.pages[3],
    site: FAKE_MODEL,
    params: {},
    i18n: t({ home: 'Home' }),
  });
  assert.equal(
    nested,
    '<nav class="breadcrumbs"><a href="/">Home</a><span class="crumb-sep">/</span>' +
    '<a href="/posts/">Posts</a><span class="crumb-sep">/</span><span>Post A</span></nav>'
  );
  const topLevel = await gen({
    page: FAKE_MODEL.pages[2],
    site: FAKE_MODEL,
    params: {},
    i18n: t({ home: 'Home' }),
  });
  assert.equal(
    topLevel,
    '<nav class="breadcrumbs"><a href="/">Home</a><span class="crumb-sep">/</span><span>About</span></nav>'
  );
});

test('breadcrumbs skips sections and escapes special characters', async () => {
  const gen = await loadGen('breadcrumbs');
  assert.equal(await gen({ page: FAKE_MODEL.pages[1], site: FAKE_MODEL, params: {}, i18n: t({}) }), '');
  const spiky = await gen({
    page: leaf('en', '/posts/x/', { title: 'Q & <R> "S"', parentLink: '/posts/' }),
    site: FAKE_MODEL,
    params: {},
    i18n: t({ home: 'Home' }),
  });
  assert.ok(spiky.includes('<span>Q &amp; &lt;R&gt; &quot;S&quot;</span>'));
});

test('breadcrumbs returns empty string for legacy-shaped siteData calls', async () => {
  const gen = await loadGen('breadcrumbs');
  assert.equal(await gen(FAKE_MODEL), '');
  assert.equal(await gen({}), '');
});

test('prev_next links date-ordered siblings with empty placeholders', async () => {
  const gen = await loadGen('prev_next');
  const first = await gen({
    page: FAKE_MODEL.pages[3],
    site: FAKE_MODEL,
    params: {},
    i18n: t({ previous_page: 'Previous', next_page: 'Next' }),
  });
  assert.equal(first, '<nav class="prev-next"><span></span><a href="/posts/b/" class="pn-next">Next: Post B</a></nav>');
  const last = await gen({
    page: FAKE_MODEL.pages[4],
    site: FAKE_MODEL,
    params: {},
    i18n: t({ previous_page: 'Previous', next_page: 'Next' }),
  });
  assert.equal(last, '<nav class="prev-next"><a href="/posts/a/" class="pn-prev">Previous: Post A</a><span></span></nav>');
});

test('prev_next skips sections and lonely pages', async () => {
  const gen = await loadGen('prev_next');
  assert.equal(await gen({ page: FAKE_MODEL.pages[1], site: FAKE_MODEL, params: {}, i18n: t({}) }), '');
  assert.equal(await gen({ page: FAKE_MODEL.pages[2], site: FAKE_MODEL, params: {}, i18n: t({}) }), '');
  assert.equal(await gen(FAKE_MODEL), '');
});

test('prev_next escapes sibling titles', async () => {
  const gen = await loadGen('prev_next');
  const model = {
    config: FAKE_MODEL.config,
    pages: [
      leaf('en', '/p/', { title: 'P', isSection: true }),
      leaf('en', '/p/x/', { title: '<X> & Co', date: '2026-01-01', parentLink: '/p/' }),
      leaf('en', '/p/y/', { title: 'Y', date: '2026-01-02', parentLink: '/p/' }),
    ],
  };
  const html = await gen({ page: model.pages[2], site: model, params: {}, i18n: t({ previous_page: 'Prev' }) });
  assert.ok(html.includes('class="pn-prev">Prev: &lt;X&gt; &amp; Co</a>'));
});

test('lang_nav shows only other locales, no active marker', async () => {
  const gen = await loadGen('lang_nav');
  const html = await gen({ page: FAKE_MODEL.pages[4], site: FAKE_MODEL });
  assert.equal(
    html,
    '<nav class="lang-nav">' +
    '<a href="/ru/posts/b/" class="lang-link"><span class="lang-cur">en</span><span class="lang-sep">/</span><span class="lang-alt">ru</span></a></nav>'
  );
});

test('lang_nav falls back to locale home when translation missing', async () => {
  const gen = await loadGen('lang_nav');
  const html = await gen({ page: FAKE_MODEL.pages[3], site: FAKE_MODEL });
  assert.equal(
    html,
    '<nav class="lang-nav">' +
    '<a href="/ru/" class="lang-link"><span class="lang-cur">en</span><span class="lang-sep">/</span><span class="lang-alt">ru</span></a></nav>'
  );
});

test('lang_nav stays empty for single-locale sites', async () => {
  const gen = await loadGen('lang_nav');
  const solo = {
    config: { site: { locales: [{ code: 'en', output_prefix_override: '' }] } },
    pages: [leaf('en', '/', { title: 'Solo', isSection: true }), leaf('en', '/a/', { title: 'A' })],
  };
  assert.equal(await gen({ page: solo.pages[1], site: solo }), '');
});

test('header escapes HTML-special characters in rendered titles', async () => {
  const gen = await loadGen('header');
  const fallback = await gen({ page: page('xx', '/xx/'), site: MODEL, params: { title: 'A <b>&</b> "B"' } });
  assert.equal(fallback, '<a href="/" class="site-title">A &lt;b&gt;&amp;&lt;/b&gt; &quot;B&quot;</a>');
  const titled = {
    ...MODEL,
    pages: [page('ru', '/ru/', 'H "ome" <1>'), page('ru', '/x/')],
  };
  const home = await gen({ page: titled.pages[1], site: titled, params: {} });
  assert.equal(home, '<a href="/ru/" class="site-title">H &quot;ome&quot; &lt;1&gt;</a>');
});
